=== tomFlidr/tomflidr.cz/Var/Document.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="/doc" 
	xmlns:pur="/doc"
	attributeFormDefault="unqualified" 
	elementFormDefault="qualified" >
	<xsd:element name="data">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="title" type="xsd:string" />
				<xsd:element name="sequence" type="xsd:int" />
				<xsd:element name="active" type="xsd:boolean" />
				<xsd:element name="controller" type="xsd:string" />
				<xsd:element name="action" type="xsd:string" />
				<xsd:element name="description" type="xsd:string" />
				<xsd:element name="keywords" type="xsd:string" />
				<xsd:element name="robots" type="xsd:string" />
				<xsd:element name="og-image" type="xsd:string" />
				<xsd:element name="og-title" type="xsd:string" />
				<xsd:element name="og-description" type="xsd:string" />
				<xsd:element name="itemprop-name" type="xsd:string" />
				<xsd:element name="itemprop-description" type="xsd:string" />
				<xsd:element name="navigation-title" type="xsd:string" />
				<xsd:element name="navigation-subtitle" type="xsd:string" />
				<xsd:element name="perex" type="xsd:string" />
				<xsd:element name="body">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
						</xsd:sequence>
						<xsd:anyAttribute processContents="skip"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== tomFlidr/tomflidr.cz/Var/Documents/de/kontakte.xml
<?xml version="1.0" encoding="utf-8" ?>
<doc:data xsi:schemaLocation="/doc ../../Document.xsd" xmlns:doc="/doc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<doc:title>Kontakte</doc:title>
	<doc:sequence>6</doc:sequence>
	<doc:active>1</doc:active>
	<doc:controller></doc:controller>
	<doc:action>Contact</doc:action>
	<doc:description></doc:description>
	<doc:keywords></doc:keywords>
	<doc:robots></doc:robots>
	<doc:og-image></doc:og-image>
	<doc:og-title></doc:og-title>
	<doc:og-description></doc:og-description>
	<doc:itemprop-name></doc:itemprop-name>
	<doc:itemprop-description></doc:itemprop-description>
	<doc:navigation-title></doc:navigation-title>
	<doc:navigation-subtitle>rufen mich gerne an</doc:navigation-subtitle>
	<doc:perex></doc:perex>
	<doc:body>
		<h1><?=$this->title?></h1>
		
	</doc:body>
</doc:data>

=== tomFlidr/tomflidr.cz/Var/Documents/en.xml
<?xml version="1.0" encoding="utf-8" ?>
<doc:data xsi:schemaLocation="/doc ../Document.xsd" xmlns:doc="/doc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<doc:title>Tom Fl√≠dr | freelance web developer, trainer &amp; consultant</doc:title>
	<doc:sequence>1</doc:sequence>
	<doc:active>1</doc:active>
	<doc:controller></doc:controller>
	<doc:action></doc:action>
	<doc:description></doc:description>
	<doc:keywords></doc:keywords>
	<doc:robots></doc:robots>
	<doc:og-image></doc:og-image>
	<doc:og-title></doc:og-title>
	<doc:og-description></doc:og-description>
	<doc:itemprop-name></doc:itemprop-name>
	<doc:itemprop-description></doc:itemprop-description>
	<doc:navigation-title>Home</doc:navigation-title>
	<doc:navigation-subtitle>so from beginning</doc:navigation-subtitle>
	<doc:perex></doc:perex>
	<doc:body>
		
		<h1><?=$this->appName?></h1>
	
		<blockquote>
			I love to create unusually specialized tools that make work-life easier for me, 
			people around or people on my IT courses. Experience in IT has taught me, that time is money, 
			therefore it decides about the developer quality, how well he can weigh these two things 
			against his inappropriate precision of source code :-)
		</blockquote>
		
	</doc:body>
</doc:data>

=== tomFlidr/tomflidr.cz/Var/Documents/de/programmierkurse-fur-fachkrafte.xml
<?xml version="1.0" encoding="utf-8" ?>
<doc:data xsi:schemaLocation="/doc ../../Document.xsd" xmlns:doc="/doc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<doc:title>Programmierkurse für Fachkräfte</doc:title>
	<doc:sequence>2</doc:sequence>
	<doc:active>0</doc:active>
	<doc:controller>Fronts\Training</doc:controller>
	<doc:action></doc:action>
	<doc:description></doc:description>
	<doc:keywords></doc:keywords>
	<doc:robots></doc:robots>
	<doc:og-image></doc:og-image>
	<doc:og-title></doc:og-title>
	<doc:og-description></doc:og-description>
	<doc:itemprop-name></doc:itemprop-name>
	<doc:itemprop-description></doc:itemprop-description>
	<doc:navigation-title>Programmierkurse</doc:navigation-title>
	<doc:navigation-subtitle>für Profis</doc:navigation-subtitle>
	<doc:perex></doc:perex>
	<doc:body>
		<h1>{$title}</h1>

	</doc:body>
</doc:data>
